name: Runtime Upgrade

on:
  pull_request:
    branches: [main, testnet]

jobs:
  migrations-duration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set-Up
        run: |
          sudo apt-get update
          sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl protobuf-compiler

      - name: Configure rustc version
        run: |
          source ci/env
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2

      - name: Build SUT
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features try-runtime

      - name: Download try-runtime snapshots data for Creditcoin
        run: |
            curl --silent https://creditcoinblockchain.blob.core.windows.net/latestblocks/creditcoin-2.0-mainnet-try-runtime-snapshot-12-19-22.tar.gz > snapshot.tar.gz

            mkdir /var/tmp/blockchain-snapshot
            tar -xzvf ./snapshot.tar.gz -C /var/tmp/blockchain-snapshot

      - name: Try-runtime migrations
        run: |
            ./target/release/creditcoin-node try-runtime --dev --no-spec-check-panic on-runtime-upgrade snap --snapshot-path /var/tmp/blockchain-snapshot
